sitani/sitani/urls.py
from django.contrib import admin
from django.urls import path
from app_sitani.views import *
from django.contrib.auth.views import LogoutView
from app_sitani import views
from django.conf import settings
from django.conf.urls.static import static
from dashboard.views import *


urlpatterns = [
#login admin django
    path('admin/', admin.site.urls),
#homepage
    path('',views.home , name='home'),
    path('home/',views.home , name = 'home'),
    path('blog/', views.blog , name ='blog'),
    path('blogsingle/<int:Id_Berita>/', blog_single, name='blogsingle'),
    path('struktur/',views.struktur, name ='struktur'),
    path('toko/', views.toko , name ='toko'),
    path('perban/', perban, name='perban'),
#dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
#login dan logout serta register
    path('login/',login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('lupasandi/', lupasandi, name='lupasandi'),
#kelola kelompok tani
    path('keltan/', keltan, name='keltan'),
    path('tambah_keltan/', tambah_keltan, name='tambah_keltan'),
    path('keltan/ubah/<str:Nama_Poktan>/', ubah_keltan, name='ubah_keltan'),
    path('keltan/hapus/<str:Nama_Poktan>/',hapus_keltan, name='hapus_keltan'),
#kelola data pegawai
    path('datapegawai/', datapegawai, name='datapegawai'),
    path('tambah_datapegawai/', tambah_datapegawai, name='tambah_datapegawai'),
    path('datapegawai/ubah/<str:Nama>/', ubah_datapegawai, name='ubah_datapegawai'),
    path('datapegawai/hapus/<str:Nama>/',hapus_datapegawai, name='hapus_datapegawai'),
#kelola toko pertanian
    path('tokopertanian/', tokopertanian, name='tokopertanian'),
    path('tambah_tokopertanian/', tambah_tokopertanian, name='tambah_tokopertanian'),
    path('tokopertanian/ubah/<str:Nama_Toko>/', ubah_tokopertanian, name='ubah_tokopertanian'),
    path('tokopertanian/hapus/<str:Nama_Toko>/', hapus_tokopertanian, name='hapus_tokopertanian'),
#kelola bantuan
    path('bantuan/', bantuan, name='bantuan'),
    path('tambah_bantuan/', tambah_bantuan, name='tambah_bantuan'),
    path('bantuan/ubah/<int:Id_Bantuan>/', ubah_bantuan, name='ubah_bantuan'),
    path('bantuan/hapus/<int:Id_Bantuan>/', hapus_bantuan, name='hapus_bantuan'),
#kelola bantuan dari pemerintah
    path('banpemtan/', banpemtan, name='banpemtan'),
    path('tambah_banpemtan/', tambah_banpemtan, name='tambah_banpemtan'),
    path('banpemtan/ubah/<str:Nama_Barang>/', ubah_banpemtan, name='ubah_banpemtan'),
    path('banpemtan/hapus/<str:Nama_Barang>/', hapus_banpemtan, name='hapus_banpemtan'),
#kelola berita
    path('beritapertanian/', beritapertanian, name='beritapertanian'),
    path('tambah_berita/', tambah_berita, name='tambah_berita'),
    path('beritapertanian/ubah/<str:Judul_Berita>/', ubah_berita, name='ubah_berita'),
    path('beritapertanian/hapus/<str:Judul_Berita>/', hapus_berita, name='hapus_berita'),
#kelola Golongan
    path('golongan/', golongan, name='golongan'),
    path('tambah_golongan/', tambah_golongan, name='tambah_golongan'),
    path('golongan/ubah/<int:Id_Golongan>/', ubah_golongan, name='ubah_golongan'),
    path('golongan/hapus/<int:Id_Golongan>/',hapus_golongan, name='hapus_golongan'),
#kelola Jabatan
    path('jabatan/', jabatan, name='jabatan'), 
    path('tambah_jabatan/', tambah_jabatan, name='tambah_jabatan'),
    path('jabatan/ubah/<str:Nama_Jabatan>/', ubah_jabatan, name='ubah_jabatan'),
    path('jabatan/hapus/<str:Nama_Jabatan>/',hapus_jabatan, name='hapus_jabatan'),
#kelola pdf
    path('bantuan_excel/',usulanbantuan_excel, name='bantuan_excel'),
    path('Status_bantuan_pdf/',statusbantuan_pdf, name='bantuan_pdf'),
    path('bantuanpemerintah_pdf/', bantuanpemerintah_pdf, name='bantuanpemerintah_pdf'),
#kelola User
    path('user/', user, name='user'),
    path('tambah_user/', tambah_user, name='tambah_user'),
#   path('user/ubah/<int:id>/', ubah_user, name='ubah_user'),
    path('user/hapus/<int:id>/', hapus_user, name='hapus_user'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitani/app_sitani/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime,timedelta
from multiselectfield import MultiSelectField
# Create your models here.
    
#kelompok Tani    
class KelompokTani(models.Model):
    Komoditas_Choise = (
        ('Padi','Padi'),
        ('Palawija','Palawija'),
        ('Cabai','Cabai'),
        ('Jamur','Jamur'),
        ('Ternak','Ternak'),
        ('Sapi Potong','Sapi Potong'),
        ('KWT','KWT'),
        ('Pemuda Tani','Pemuda Tani'),
    )
    Desa_Choise = (
        ('Cidahu','Cidahu'),
        ('Balingbing','Balingbing'),
        ('Cidadap','Cidadap'),
        ('Pangsor','Pangsor'),
        ('Bendungan','Bendungan'),
        ('Munjul','Munjul'),
        ('Margahayu','Margahayu'),
        ('Mekarwangi','Mekarwangi'),
    )
    Kelas_Choise = (
        ('Pemula','Pemula'),
        ('Lanjut','Lanjut'),
        ('Madya','Madya'),
        ('Utama','Utama'),
    )
    Status_Choise = (
        ('Aktif','Aktif'),
        ('Tidak Aktif','Tidak Aktif'),
    )
    Id_Poktan = models.AutoField(primary_key=True)
    Nama_Poktan = models.CharField(max_length=25)
    Kecamatan = models.CharField (max_length=30)
    Desa = models.CharField(choices=Desa_Choise, max_length=100, null=True)
    Ketua = models.CharField(max_length=25)
    NIK_Ketua = models.CharField(max_length=16)
    KTP_Ketua = models.ImageField(upload_to='ktp/%Y/%m/%d/', null=True, blank=True)
    Sekretaris = models.CharField(max_length=25)
    Bendahara = models.CharField(max_length=25)
    Pemilik_Lahan = models.CharField(max_length=25, null=True)
    Surat_Lahan = models.ImageField(upload_to='surat/%Y/%m/%d/', null=True, blank=True)
    No_Telephone = models.CharField(max_length=13)
    Komoditas = MultiSelectField(choices= Komoditas_Choise, max_choices=10,max_length=100)
    Score = models.IntegerField(null=True)
    Luas_Areal_HA = models.IntegerField(null=True)
    Jumlah_Anggota = models.IntegerField(null=True)
    Tanggal_Pembentukan = models.DateField(blank=True)
    Status_Poktan = models.CharField(choices=Status_Choise, max_length=100, null=True)
    Kelas_Poktan = models.CharField(choices=Kelas_Choise, max_length=100, null=True)
    
    def __str__(self):
        return self.Nama_Poktan

    
#Golongan
class Golongan(models.Model):
    Id_Golongan = models.AutoField(primary_key=True)
    Golongan = models.CharField(max_length=6, default='IA')
    Jabatan_Fungsional = models.CharField(max_length=40)
    
    def __str__(self):
        return f'{self.Golongan}-{self.Jabatan_Fungsional}'

    
#Jabatan
class Jabatan(models.Model):
    Id_Jabatan = models.AutoField(primary_key=True)
    Nama_Jabatan = models.CharField(max_length=100)
    
    def __str__(self):
        return self.Nama_Jabatan


#Profile  
class Profile(models.Model):
    NIP = models.CharField(max_length=18, primary_key=True, null=False)
    Nama = models.CharField(max_length=100)
    Id_Jabatan = models.ForeignKey('Jabatan', on_delete=models.CASCADE, null=True)
    Id_Golongan = models.ForeignKey('Golongan', on_delete=models.CASCADE, null=True)
    Foto_Profile = models.ImageField(upload_to='images/%Y/%m/%d/', null=True, blank=True)
    Alamat = models.TextField()
  
    def __str__(self):
        return self.NIP

    
#Toko Pertanian
class TokoPertanian(models.Model):
    Id_Toko = models.AutoField(primary_key=True)
    Nama_Toko = models.CharField(max_length=50)
    Nama_Pemilik = models.CharField(max_length=50, null=True)
    Foto_Toko = models.ImageField(upload_to='toko/%Y/%m/%d/', null=True, blank=True)
    Deskripsi = models.CharField(max_length=100, null=True)
    Alamat = models.TextField()
    Jam_Buka = models.TimeField()
    Jam_Tutup = models.TimeField()

    def __str__(self):
        return self.Id_Toko
 
    
class UsulanBantuanPoktan(models.Model):
    Status_Choices = (
        ('Dapat Bantuan', 'Dapat Bantuan'),
        ('Tidak Dapat', 'Tidak Dapat'),
        ('Diajukan', 'Diajukan'),
    )
    Id_Bantuan = models.AutoField(primary_key=True)
    Id_Poktan = models.ForeignKey('KelompokTani', on_delete=models.CASCADE, null=True)
    Id_Banpem = models.ForeignKey('BarangDariPemerintah', on_delete=models.CASCADE, null=True)
    Jumlah_Bantuan = models.IntegerField()
    Satuan_Bantuan = models.CharField(max_length=50)
    Tanggal_Bantuan = models.DateField(blank=True)
    Gambar_Lokasi = models.ImageField(upload_to='bantuan/%Y/%m/%d/', null=True, blank=True)
    Status = models.CharField(choices=Status_Choices, max_length=100, null=True)
    
    def Ketua(self):
        if self.Id_Poktan:
            return self.Id_Poktan.Ketua
        return None
    
    def NIK_Ketua(self):
        if self.Id_Poktan:
            return self.Id_Poktan.NIK_Ketua
        return None
    
    def No_Telephone(self):
        if self.Id_Poktan:
            return self.Id_Poktan.No_Telephone
        return None

    def Kecamatan(self):
        if self.Id_Poktan:
            return self.Id_Poktan.Kecamatan
        return None
    
    def Desa(self):
        if self.Id_Poktan:
            return self.Id_Poktan.Desa
        return None
    
    def Jumlah_Anggota(self):
        if self.Id_Poktan:
            return self.Id_Poktan.Jumlah_Anggota
        return None 
    
    def Komoditas(self):
        if self.Id_Poktan:
            return self.Id_Poktan.Komoditas
        return None
    
    def Luas_Areal_HA(self):
        if self.Id_Poktan:
            return self.Id_Poktan.Luas_Areal_HA
        return None

    def Status_Poktan(self):
        if self.Id_Poktan:
            return self.Id_Poktan.Status_Poktan
        return None

    def Kelas_Poktan(self):
        if self.Id_Poktan:
            return self.Id_Poktan.Kelas_Poktan
        return None
    
        
    def delete(self, *args, **kwargs):
        if self.Id_Banpem and self.Jumlah_Bantuan:
            barang = self.Id_Banpem
            barang.Jumlah_Barang += self.Jumlah_Bantuan
            barang.save()

        super().delete(*args, **kwargs)
        
    from datetime import datetime, timedelta

def save(self, *args, **kwargs):
    if self.Id_Banpem and self.Jumlah_Bantuan:
        barang = self.Id_Banpem
        if barang.Jumlah_Barang == 0:
            message = "Tidak dapat menambahkan BantuanPoktan karena Jumlah_Barang pada Id_Banpem sudah mencapai 0."
            raise Exception(message)

        if self.Jumlah_Bantuan > barang.Jumlah_Barang:
            message = "Tidak dapat menambahkan BantuanPoktan karena Jumlah_Bantuan melebihi Jumlah_Barang pada Id_Banpem."
            raise Exception(message)

        super().save(*args, **kwargs)  # Simpan objek BantuanPoktan ke database

        # Ambil objek BantuanPoktan yang sudah disimpan untuk mendapatkan Id_Bantuan yang terbaru
        instance = UsulanBantuanPoktan.objects.get(Id_Bantuan=self.Id_Bantuan)

        if self.Jumlah_Bantuan > instance.Jumlah_Bantuan:
            # Pengurangan yang dilakukan hanya jika self.Jumlah_Bantuan lebih besar daripada instance.Jumlah_Bantuan
            difference = self.Jumlah_Bantuan - instance.Jumlah_Bantuan
            barang.Jumlah_Barang -= difference
            barang.save()
    else:
        super().save(*args, **kwargs)
        
        # Tambahkan logika untuk mengecualikan kelompok tani dengan status "Dapat Bantuan" dari daftar tahun berikutnya
        if self.status == "Dapat Bantuan":
            next_year = datetime.now().year + 1
            kelompok_tani = KelompokTani.objects.filter(Nama_Poktan=self.Nama_Poktan, tahun__gte=next_year)
            kelompok_tani.update(tampilkan=False)
            message = "Kelompok Tani ini Sudah Mendapatkan Bantuan di tahun sekarang."
            self.add_error(None, message)


    def __str__(self):
        return self.Id_Bantuan
       
#Barang Dari Pemerintah
class BarangDariPemerintah(models.Model):
    Id_Banpem = models.AutoField(primary_key=True)
    Nama_Barang = models.CharField(max_length=100)
    Jumlah_Barang = models.IntegerField()
    Satuan = models.CharField(max_length=100)
    Tanggal = models.DateField(blank=True)
    
    def __str__(self):
        return self.Nama_Barang
    

#Berita Pertanian 
class BeritaPertanian(models.Model):
    Id_Berita = models.AutoField(primary_key=True)
    Penulis = models.CharField(max_length=30, null=True)
    Judul_Berita = models.CharField(max_length=100)
    Foto_Berita = models.ImageField(upload_to='berita/%Y/%m/%d/', null=True, blank=True)
    Isi_Berita = models.TextField()
    Jam_Update = models.TimeField()
    Tanggal_Update = models.DateField(blank=True)

    def __str__(self):
        return self.Id_Berita

sitani/dashboard/models.py
from django.db import models

# Create your models here.

sitani/dashboard/views.py
from django.shortcuts import render, redirect
from app_sitani.models import KelompokTani, BeritaPertanian, UsulanBantuanPoktan,TokoPertanian, Profile, BarangDariPemerintah, Golongan, Jabatan
from app_sitani.forms import FormBantuanPoktan,FormProfilePegawai, FormRegister, FormKeltan, FormBerita, FormToko, FormBarangDariPemerintah, LupaSandi, FormGolongan, FormJabatan
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth import authenticate,login
from django.contrib.auth.forms import UserCreationForm
from django.db import connection
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect,HttpRequest,HttpResponseForbidden
from django.http import FileResponse
from django.core.exceptions import ValidationError


# Create your views here.
def dashboard (request):
    return HttpResponse('dashboard.html')

sitani/dashboard/templates/banpemtan.html
{% extends 'base.html' %}

{% block content %}

<!-- Page Heading -->
<h1 class="h3 mb-0 text-gray-800">Data Bantuan Dari Pemerintah</h1>
<p class="mb-4">Halaman ini digunakan untuk melakukan pengelolaan data Bantuan Pemerintah.</p>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            <div class="btn-group mr-2">
                <a href="{% url 'tambah_banpemtan' %}" class="btn btn-primary">Tambah Bantuan Pemerintah</a>
            </div>
            <div class="btn-group mr-2">
                <a href="{% url 'bantuanpemerintah_pdf' %}" class="btn btn-primary">Laporan</a>
            </div>
        </h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            {% for message in messages %}
                {% if message %}
                    <div class="alert alert-success">{{ message }}</div>
                {% endif %}
            {% endfor %}
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nama Bantuan</th>
                        <th>Jumlah Barang</th>
                        <th>Satuan</th> 
                        <th>Tanggal</th> 
                        <th>Aksi</th> 
                    </tr>
                </thead>
                <tbody>
                    {% for banpemtan in banpem %}
                        <tr>
                            <td>{{ banpemtan.Nama_Barang }}</td>
                            <td>{{ banpemtan.Jumlah_Barang }}</td>
                            <td>{{ banpemtan.Satuan }}</td>
                            <td>{{ banpemtan.Tanggal}}</td>
                            <td>
                                <div class="btn-group">
                                    <a href="{% url 'ubah_banpemtan' banpemtan.Id_Banpem %}" class="btn btn-primary d-inline-block">Edit</a>
                                    <button data-toggle="modal" data-target="#hapus-{{ banpemtan.Id_Banpem }}" class="btn btn-danger">Hapus</button>
                                    
                                </div>
                            </td>
                            <div class="modal" id="hapus-{{ banpemtan.Id_Banpem }}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h3 class="modal-title">Hapus</h3>
                                        </div>
                                        <div class="modal-body">
                                            Apakah Anda yakin ingin menghapus <strong>{{ banpemtan.Nama_Barang | upper }}</strong>?
                                        </div>
                                        <div class="modal-footer">
                                            <a href="{% url 'hapus_banpemtan' banpemtan.Id_Banpem %}" class="btn btn-danger">Hapus</a>
                                            <button class="btn btn-primary" data-dismiss="modal">Tidak</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>  

{% endblock %}

sitani/dashboard/templates/bantuan.html
{% extends 'base.html' %}

{% block content %}

<!-- Page Heading -->
<h1 class="h3 mb-0 text-gray-800">Data Usulan Bantuan Kelompok Tani</h1>
<p class="mb-4">Halaman ini digunakan untuk melakukan pengelolaan data usulan bantuan Kelompok Tani di Pagaden Barat.</p>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            <div class="btn-group mr-2">
                <a href="{% url 'tambah_bantuan' %}" class="btn btn-primary">Tambah Usulan Bantuan Poktan</a>
            </div>
            <div class="btn-group mr-2">
                <a href="{% url 'bantuan_excel' %}" class="btn btn-primary">Laporan</a>
            </div>
        </h6>
    </div>  
    <div class="card-body">
        <div class="table-responsive">
            {% for message in messages %}
                {% if message %}
                    <div class="alert alert-success">{{ message }}</div>
                {% endif %}
            {% endfor %}
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nama Kelompok Tani</th>
                        <th>Nama Bantuan</th>
                        <th>Desa</th>
                        <th>Kecamatan</th>
                        <th>Ketua</th>
                        <th>NIK</th>
                        <th>No Telephone</th>
                        <th>Komoditas</th> 
                        <th>Luas Areal HA</th>
                        <th>Status Poktan</th>
                        <th>Kelas Poktan</th>
                        <th>Jumlah_Anggota</th>
                        <th>Jumlah Bantuan</th>
                        <th>Satuan Bantuan</th>
                        <th>Tanggal Bantuan</th> 
                        <th>Gambar Lokasi</th> 
                        <th>Status Pengajuan</th> 
                        <th>Aksi</th> 
                    </tr>
                </thead>
                <tbody>
                    {% for bantuan in banpoktan %}
                        <tr>
                            <td>{{ bantuan.Id_Poktan }}</td>
                            <td>{{ bantuan.Id_Banpem }}</td>
                            <td>{{ bantuan.Desa }}</td>
                            <td>{{ bantuan.Kecamatan }}</td>
                            <td>{{ bantuan.Ketua }}</td>
                            <td>{{ bantuan.NIK_Ketua }}</td>
                            <td>{{ bantuan.No_Telephone }}</td>
                            <td>{{ bantuan.Komoditas}}</td>
                            <td>{{ bantuan.Luas_Areal_HA}}</td>
                            <td>{{ bantuan.Status_Poktan }}</td>
                            <td>{{ bantuan.Kelas_Poktan}}</td>
                            <td>{{ bantuan.Jumlah_Anggota }}</td>
                            <td>{{ bantuan.Jumlah_Bantuan }}</td>
                            <td>{{ bantuan.Satuan_Bantuan }}</td>
                            <td>{{ bantuan.Tanggal_Bantuan }}</td>
                            <td>
                                {% if bantuan.Gambar_Lokasi %}
                                    <img src="{{ bantuan.Gambar_Lokasi.url }}" img width= 60%>
                                {% endif %}
                            </td>
                            <td>  
                                    {% if bantuan.Status == 'Dapat Bantuan' %}
                                        <span class="badge badge-success">Dapat Bantuan</span>
                                    {% elif bantuan.Status == 'Diajukan' %}
                                        <span class="badge badge-warning">Diajukan</span>
                                    {% elif bantuan.Status == 'Tidak Dapat' %}
                                        <span class="badge badge-danger">Tidak Dapat</span>
                                    {% endif %}
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a href="{% url 'ubah_bantuan' bantuan.Id_Bantuan %}" class="btn btn-primary d-inline-block">Edit</a>
                                    <button data-toggle="modal" data-target="#hapus-{{ bantuan.Id_Bantuan }}" class="btn btn-danger">Hapus</button>
                                    
                                </div>
                            </td>
                            <div class="modal" id="hapus-{{ bantuan.Id_Bantuan }}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h3 class="modal-title">Hapus</h3>
                                        </div>
                                        <div class="modal-body">
                                            Apakah Anda yakin ingin menghapus <strong>{{ bantuan.Id_Poktan| upper }}</strong>?
                                        </div>
                                        <div class="modal-footer">
                                            <a href="{% url 'hapus_bantuan' bantuan.Id_Bantuan %}" class="btn btn-danger">Hapus</a>
                                            <button class="btn btn-primary" data-dismiss="modal">Tidak</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>  

{% endblock %}

sitani/dashboard/templates/tambah-bantuan.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Tambah Usulan Bantuan untuk Kelompok Tani:</h3>
            {% if messages %}
                <div class="alert alert-success">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
            {% endif %}

            <form action="{% url 'tambah_bantuan' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_Id_Poktan">Nama Kelompok Tani</label>
                    {{ form.Id_Poktan }}
                </div>
                <div class="form-group">
                    <label for="id_Id_Banpem">Nama Bantuan Dari Pemerintah</label>
                    {{ form.Id_Banpem }}
                </div>
                <div class="form-group">
                    <label for="id_Jumlah_Bantuan">Jumlah Bantuan</label>
                    {{ form.Jumlah_Bantuan }}
                </div>
                <div class="form-group">
                    <label for="id_Satuan_Bantuan">Satuan</label>
                    {{ form.Satuan_Bantuan }}
                </div>
                <div class="form-group">
                    <label for="id_Tanggal_Bantuan">Tanggal</label>
                    {{ form.Tanggal_Bantuan }}
                </div>
                <div class="form-group">
                    <label for="id_Gambar_Lokasi">Gambar Lokasi</label>
                    {{ form.Gambar_Lokasi }}
                </div>
                <div class="form-group">
                    <label for="id_Status">Status Pengajuan</label>
                    {{ form.Status }}
                </div>
                <button class="btn btn-danger">Tambah Bantuan</button>
                <a href="{% url 'bantuan' %}" class="btn btn-primary">Kembali</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

sitani/dashboard/templates/tambah-datapegawai.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class ="col-md-4">
        <h3>Tambah Data Pegawai :</h3>
      {% if pesan %}
        <div class="alert alert-success">
            {{pesan}}
        </div>
        {% endif %}

        <form method="post" action="{% url 'tambah_datapegawai' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_NIP">NIP</label>
                {{ form.NIP }}
            </div>
            <div class="form-group">
                <label for="id_Nama">Nama Pegawai UPTD Pertanian Pagaden Barat</label>
                {{ form.Nama }}
            </div>
            <div class="form-group">
                <label for="id_Foto_profile">Foto Profile</label>
                {{form.Foto_Profile  }}
            </div>
            <div class="form-group">
                <label for="id_Id_Jabatan">Jabatan</label>
                {{ form.Id_Jabatan }}
            </div>
            <div class="form-group">
                <label for="id_Id_Golongan">Golongan</label>
                {{ form.Id_Golongan }}
            </div>
            <div class="form-group">
                <label for="id_Alamat">Alamat</label>
                {{ form.Alamat }}
            </div>
            <button class="btn btn-danger">Tambah Data Pegawai</button>
            <a href="{% url 'datapegawai' %}" class="btn btn-priamry">Kembali</a>
        </form>
    </div>
   </div> 
</div>

<br>
<br>

{% endblock %}

sitani/dashboard/templates/tambah-toko.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class ="col-md-4">
        <h3>Tambah Toko Pertanian :</h3>
      {% if pesan %}

        <div class="alert alert-success">
            {{pesan}}
        </div>

        {% endif %}

        <form method="post" action="{% url 'tambah_tokopertanian' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-danger">Tambah Toko</button>
            <a href="{% url 'tokopertanian' %}" class="btn btn-priamry">Kembali</a>
        </form>
    </div>
   </div> 
</div>

<br>
<br>

{% endblock %}

sitani/dashboard/templates/ubah-banpemtan.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4>Ubah Data Bantuan Dari Pemerintah</h4>
            
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success">{{ message }}</div>
                {% elif message.tags == 'error' %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% endif %}
            {% endfor %}

            <form action="{% url 'ubah_banpemtan' banpem.Id_Banpem %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_Nama_Barang">Nama Barang</label>
                    {{ form.Nama_Barang }}
                </div>
                <div class="form-group">
                    <label for="id_Jumlah_Barang"> Jumlah Barang</label>
                    {{ form.Jumlah_Barang }}
                </div>
                <div class="form-group">
                    <label for="id_Satuan">Satuan</label>
                    {{ form.Satuan }}
                </div>
                <div class="form-group">
                    <label for="id_Tanggal">Tanggal</label>
                    {{ form.Tanggal }}
                </div>           
                <button class="btn btn-danger">Simpan</button>
                <a href="{% url 'banpemtan' %}"  class="btn btn-primary">Kembali</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}